{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ecaa787-7eb9-4434-b4f1-44d12ce72f9f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "# ===============================================================\n",
    "#\n",
    "#   九合一新聞爬蟲 (CNA, UDN, SETN, TVBS, EBC, NOWnews, ETtoday, LTN, ChinaTimes)\n",
    "#   版本: v14 (2025-11-10 - 全新資料集版)\n",
    "#\n",
    "#   - 依使用者要求，將輸出檔案改為 'news_dataset.csv'。\n",
    "#   - 建立新的 'news_dataset_cache.json'，以確保抓取全新資料。\n",
    "#   - 整合 v13 所有媒體的爬蟲修復。\n",
    "#\n",
    "# ===============================================================\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 1: 環境設定、全域變數與路徑\n",
    "# ===============================================================\n",
    "import sys\n",
    "import subprocess\n",
    "import importlib\n",
    "import logging\n",
    "import os\n",
    "from datetime import datetime, timezone, timedelta\n",
    "import requests\n",
    "from bs4 import BeautifulSoup\n",
    "import pandas as pd\n",
    "import json\n",
    "import re\n",
    "import time\n",
    "import lxml # 雖然程式碼中可能沒有顯式呼叫 lxml，但 bs4 會使用它來加速解析\n",
    "\n",
    "# --- 設定路徑 ---\n",
    "# 讓腳本在 crontab 中也能正確找到檔案\n",
    "try:\n",
    "    # __file__ 變數只在 .py 檔案被執行時存在\n",
    "    BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n",
    "except NameError:\n",
    "    # 當在 Jupyter Notebook 或類似環境中執行時，使用 getcwd()\n",
    "    BASE_DIR = os.getcwd() \n",
    "\n",
    "# *** v14 變更：使用新的檔案名稱 ***\n",
    "DB_FILENAME = os.path.join(BASE_DIR, 'news_dataset.csv')\n",
    "TEMP_JSON_FILENAME = os.path.join(BASE_DIR, 'news_dataset_cache.json')\n",
    "LOG_FILENAME = os.path.join(BASE_DIR, 'news_scraper.log') # 日誌檔保持不變\n",
    "\n",
    "# --- 設定日誌 (Logging) ---\n",
    "# 移除所有既有的日誌處理器，避免重複輸出\n",
    "for handler in logging.root.handlers[:]:\n",
    "    logging.root.removeHandler(handler)\n",
    "    \n",
    "# 設定日誌記錄：同時輸出到檔案 (LOG_FILENAME) 與終端機\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format='%(asctime)s - %(levelname)s - %(message)s',\n",
    "    handlers=[\n",
    "        logging.FileHandler(LOG_FILENAME, 'a', 'utf-8'), # 'a' = append (附加模式)\n",
    "        logging.StreamHandler(sys.stdout) # 輸出到終端機\n",
    "    ]\n",
    ")\n",
    "\n",
    "# --- 全域變數 ---\n",
    "# 統一的 HTTP Headers\n",
    "HEADERS = {\n",
    "    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'\n",
    "}\n",
    "# 欄位名稱 (必須完全符合您的 news_dataset.csv 檔案)\n",
    "SNAPSHOT_COLUMNS = [\n",
    "    'url', 'title', 'headline_level', 'snapshot_at', 'full_content', 'source', 'url_hash'\n",
    "]\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 2: 通用工具函式 (Helper Functions)\n",
    "# ===============================================================\n",
    "\n",
    "def get_current_utc_time():\n",
    "    \"\"\"回傳當前的 ISO 8601 格式 UTC 時間字串\"\"\"\n",
    "    return datetime.now(timezone.utc).isoformat()\n",
    "\n",
    "def normalize_url(base_url, relative_url):\n",
    "    \"\"\"將相對 URL 轉換為絕對 URL\"\"\"\n",
    "    if not relative_url:\n",
    "        return None\n",
    "    if relative_url.startswith(('http://', 'https://')):\n",
    "        return relative_url\n",
    "    if relative_url.startswith('//'):\n",
    "        return 'https:' + relative_url\n",
    "    # 處理 base_url 結尾沒有 / 的情況\n",
    "    if not base_url.endswith('/'):\n",
    "        base_url += '/'\n",
    "    # 處理 relative_url 開頭有 / 的情況\n",
    "    if relative_url.startswith('/'):\n",
    "        relative_url = relative_url[1:]\n",
    "    \n",
    "    # 使用 requests.compat.urljoin 進行更穩健的 URL 組合\n",
    "    return requests.compat.urljoin(base_url, relative_url)\n",
    "\n",
    "def get_soup(url, encoding=None):\n",
    "    \"\"\"\n",
    "    發送 HTTP GET 請求並回傳 BeautifulSoup 解析後的物件。\n",
    "    \"\"\"\n",
    "    try:\n",
    "        response = requests.get(url, headers=HEADERS, timeout=15)\n",
    "        response.raise_for_status() # 如果 HTTP 狀態碼不是 200，拋出例外\n",
    "        \n",
    "        if encoding:\n",
    "            response.encoding = encoding # 強制指定編碼\n",
    "        else:\n",
    "            response.encoding = response.apparent_encoding # 自動偵測編碼\n",
    "            \n",
    "        soup = BeautifulSoup(response.text, 'lxml')\n",
    "        return soup\n",
    "    except requests.exceptions.Timeout:\n",
    "        logging.warning(f\"🟡 請求超時: {url}\")\n",
    "    except requests.exceptions.HTTPError as e:\n",
    "        logging.warning(f\"🟡 HTTP 錯誤 {e.response.status_code}: {url}\")\n",
    "    except requests.exceptions.RequestException as e:\n",
    "        logging.warning(f\"🟡 請求失敗: {url} ({e})\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 解析 BeautifulSoup 失敗: {url} ({e})\")\n",
    "        \n",
    "    return None # 發生任何錯誤都回傳 None\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 3: Part 1 核心功能 (抓取頭條 URL)\n",
    "# ===============================================================\n",
    "\n",
    "def load_headlines_from_json(filepath=TEMP_JSON_FILENAME):\n",
    "    \"\"\"\n",
    "    從 JSON 檔案載入先前抓取的頭條 URL。\n",
    "    回傳一個 Set，包含所有已知的 URL。\n",
    "    \"\"\"\n",
    "    try:\n",
    "        if os.path.exists(filepath):\n",
    "            with open(filepath, 'r', encoding='utf-8') as f:\n",
    "                data = json.load(f)\n",
    "                # 確保回傳的是一個 Set，以便快速查找\n",
    "                return set(data.get('urls', []))\n",
    "        else:\n",
    "            logging.info(f\"JSON 暫存檔 {filepath} 不存在，將建立新檔案。\")\n",
    "    except json.JSONDecodeError:\n",
    "        logging.warning(f\"🟡 JSON 檔案 {filepath} 格式錯誤，將建立新檔案。\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 載入 JSON 檔案時發生錯誤: {e}\")\n",
    "    \n",
    "    return set() # 發生錯誤或檔案不存在時，回傳空 Set\n",
    "\n",
    "def save_headlines_to_json(all_urls_set, filepath=TEMP_JSON_FILENAME):\n",
    "    \"\"\"\n",
    "    將所有頭條 URL (Set) 儲存回 JSON 檔案。\n",
    "    \"\"\"\n",
    "    try:\n",
    "        data = {'urls': list(all_urls_set)} # 將 Set 轉回 List 以便 JSON 序列化\n",
    "        with open(filepath, 'w', encoding='utf-8') as f:\n",
    "            json.dump(data, f, ensure_ascii=False, indent=4)\n",
    "        logging.info(f\"✓ JSON 暫存檔 {filepath} 已更新，目前共 {len(all_urls_set)} 筆不重複 URL。\")\n",
    "    except IOError as e:\n",
    "        logging.error(f\"🔥 寫入 JSON 檔案 {filepath} 失敗: {e}\")\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 儲存 JSON 時發生未知錯誤: {e}\")\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 4: 九大媒體爬蟲函式 (v14 修復版)\n",
    "# ===============================================================\n",
    "\n",
    "# \n",
    "# (1/9) CNA 中央社 (v13 修復版)\n",
    "#\n",
    "def fetch_cna_headlines():\n",
    "    \"\"\"(1/9) 抓取 CNA 中央社 頭條\"\"\"\n",
    "    logging.info(\"--- (1/9) 正在抓取 CNA 中央社頭條 ---\")\n",
    "    base_url = 'https://www.cna.com.tw'\n",
    "    # *** 修正 (A): CNA 首頁使用 JS 動態載入，改抓取 'aall.aspx' (即時新聞列表) ***\n",
    "    list_url = 'https://www.cna.com.tw/list/aall.aspx'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    soup = get_soup(list_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 CNA 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # *** 修正 (B): 使用 'aall.aspx' 的 CSS 選擇器 ***\n",
    "        # L1 (即時新聞列表)\n",
    "        for item in soup.select('ul.main-list li a'):\n",
    "            try:\n",
    "                title = item.find('h2').get_text(strip=True) if item.find('h2') else item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'cna.com.tw' in url:\n",
    "                    # CNA 的即時列表頁沒有 L3 或 L2 的區別，因此全部標記為 L1\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'CNA'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 CNA 剖析列表項目錯誤: {e}\")\n",
    "                \n",
    "        # CNA 首頁的 L3/L2 很難抓取，我們在這裡專注於 L1，確保有資料流入\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 CNA 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 CNA 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (2/9) UDN 聯合新聞網 (v13 修復版)\n",
    "#\n",
    "def fetch_udn_headlines():\n",
    "    \"\"\"(2/9) 抓取 UDN 聯合新聞網 頭條\"\"\"\n",
    "    logging.info(\"--- (2/9) 正在抓取 UDN 聯合新聞網頭條 ---\")\n",
    "    base_url = 'https://udn.com'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    # *** 修正 (C): UDN 的 /news/breaknews 使用動態載入，改為直接抓取首頁 ***\n",
    "    soup = get_soup(base_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 UDN 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # *** 修正 (D): 更新 L3 選擇器 (首頁大圖) (2025/11/10) ***\n",
    "        # 抓取 `div.story-list__image` 和 `div.story-list__text` 下的 a 標籤\n",
    "        for item in soup.select('div.story-list__image a, div.story-list__text h2 a'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                if not title:\n",
    "                    # 備用方案：抓取 <a> 標籤內的文字\n",
    "                    title = item.get_text(strip=True)\n",
    "                \n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                if title and url and 'udn.com' in url and '/event/' not in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'UDN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 UDN Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (E): 更新 L1 選擇器 (首頁-即時新聞) (2025/11/10) ***\n",
    "        # 抓取 `section.section-breaknews` (即時新聞區塊)\n",
    "        for item in soup.select('div.context-box__content a'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                if not title:\n",
    "                    title = item.get_text(strip=True)\n",
    "                \n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                if title and url and 'udn.com' in url and '/event/' not in url:\n",
    "                    # 首頁的即時新聞歸類為 L1\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'UDN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 UDN Level 1 剖析錯誤: {e}\")\n",
    "                \n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 UDN 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 UDN 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (3/9) SETN 三立新聞網 (v12 成功版)\n",
    "#\n",
    "def fetch_setn_headlines():\n",
    "    \"\"\"(3/9) 抓取 SETN 三立新聞網 頭條\"\"\"\n",
    "    logging.info(\"--- (3/9) 正在抓取 SETN 三立新聞網頭條 ---\")\n",
    "    base_url = 'https://www.setn.com'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    soup = get_soup(base_url, encoding='utf-8')\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 SETN 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # L3 (首頁大圖)\n",
    "        for item in soup.select('div.col-sm-8.top-news a[href^=\"/News.aspx\"]'):\n",
    "            try:\n",
    "                title_tag = item.find('h1') or item.find('h2') or item.find('h3')\n",
    "                title = title_tag.get_text(strip=True) if title_tag else None\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'SETN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 SETN Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # L1 (即時清單)\n",
    "        for item in soup.select('div#gtMain-RealTime-News-scroll ul li a[href^=\"/News.aspx\"]'):\n",
    "            try:\n",
    "                title_tag = item.find('p.realtime-list-title')\n",
    "                title = title_tag.get_text(strip=True) if title_tag else item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'SETN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 SETN Level 1 剖析錯誤: {e}\")\n",
    "                \n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 SETN 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 SETN 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (4/9) TVBS 新聞網 (v12 成功版)\n",
    "#\n",
    "def fetch_tvbs_headlines():\n",
    "    \"\"\"(4/9) 抓取 TVBS 新聞網 頭條\"\"\"\n",
    "    logging.info(\"--- (4/9) 正在抓取 TVBS 新聞網頭條 ---\")\n",
    "    base_url = 'https://news.tvbs.com.tw'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "    \n",
    "    soup = get_soup(base_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 TVBS 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # L3 (首頁-大圖輪播)\n",
    "        for item in soup.select('div.focus_slider ul.slick-slider li.slick-slide a'):\n",
    "            try:\n",
    "                title = item.find('h2').get_text(strip=True) if item.find('h2') else None\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'tvbs.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'TVBS'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 TVBS Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # L2 (首頁-編輯精選)\n",
    "        for item in soup.select('div.editor_slide ul.slick-slider li.slick-slide a'):\n",
    "            try:\n",
    "                title = item.find('h2').get_text(strip=True) if item.find('h2') else None\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'tvbs.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 2, 'scraped_at': scraped_at, 'source': 'TVBS'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 TVBS Level 2 剖析錯誤: {e}\")\n",
    "\n",
    "        # L1 (首頁-即時新聞)\n",
    "        for item in soup.select('div.realtime_news ul.news_list li a'):\n",
    "            try:\n",
    "                title = item.find('h2').get_text(strip=True) if item.find('h2') else None\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'tvbs.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'TVBS'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 TVBS Level 1 剖析錯誤: {e}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 TVBS 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 TVBS 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (5/9) EBC 東森新聞 (v12 成功版)\n",
    "#\n",
    "def fetch_ebc_headlines():\n",
    "    \"\"\"(5/9) 抓取 EBC 東森新聞 頭條\"\"\"\n",
    "    logging.info(\"--- (5/9) 正在抓取 EBC 東森新聞頭條 ---\")\n",
    "    base_url = 'https://news.ebc.net.tw'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    soup = get_soup(base_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 EBC 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # L3 (首頁-大圖輪播)\n",
    "        for item in soup.select('div.news-block-style21 a.large'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'ebc.net.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'EBC'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 EBC Level 3 剖析錯誤: {e}\")\n",
    "                \n",
    "        # L2 (首頁-大圖旁次要新聞)\n",
    "        for item in soup.select('div.news-block-style21 a.small'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'ebc.net.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 2, 'scraped_at': scraped_at, 'source': 'EBC'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 EBC Level 2 剖析錯誤: {e}\")\n",
    "\n",
    "        # L1 (首頁-即時新聞)\n",
    "        for item in soup.select('div.news-list-box.style1 div.news-list-block ul li a'):\n",
    "            try:\n",
    "                title = item.find('span.title').get_text(strip=True) if item.find('span.title') else item.get('title')\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'ebc.net.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'EBC'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 EBC Level 1 剖析錯誤: {e}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 EBC 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 EBC 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (6/9) NOWnews 今日新聞 (v12 成功版)\n",
    "#\n",
    "def fetch_nownews_headlines():\n",
    "    \"\"\"(6/9) 抓取 NOWnews 今日新聞 頭條\"\"\"\n",
    "    logging.info(\"--- (6/9) 正在抓取 NOWnews 今日新聞頭條 ---\")\n",
    "    base_url = 'https://www.nownews.com'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    soup = get_soup(base_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 NOWnews 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # L3 (首頁-大圖輪播)\n",
    "        for item in soup.select('div.big-slide-news a.item-text'):\n",
    "            try:\n",
    "                title = item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'nownews.com' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'NOWnews'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 NOWnews Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # L1 (即時新聞列表)\n",
    "        # NOWnews 即時新聞頁面是動態載入，因此我們改抓首頁的 \"最新\" 區塊\n",
    "        for item in soup.select('div.tab-content[data-content=\"latest\"] div.item a'):\n",
    "            try:\n",
    "                title = item.find('h3').get_text(strip=True) if item.find('h3') else None\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'nownews.com' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'NOWnews'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 NOWnews Level 1 剖析錯誤: {e}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 NOWnews 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "        \n",
    "    logging.info(f\"💡 NOWnews 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (7/9) ETtoday 新聞雲 (v13 修復版)\n",
    "#\n",
    "def fetch_ettoday_headlines():\n",
    "    \"\"\"(7/9) 抓取 ETtoday 新聞雲 頭條\"\"\"\n",
    "    logging.info(\"--- (7/9) 正在抓取 ETtoday 新聞雲頭條 ---\")\n",
    "    base_url = 'https://www.ettoday.net'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    # *** 修正 (F): ETtoday 的 /news/news-list 使用動態載入，改為直接抓取首頁 ***\n",
    "    soup = get_soup(base_url)\n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 ETtoday 抓取失敗。\")\n",
    "        return headlines\n",
    "\n",
    "    try:\n",
    "        # *** 修正 (G): 更新 L3 選擇器 (首頁-頭條) (2025/11/10) ***\n",
    "        # 抓取 `div.c1` (主要頭條區) 和 `div.focus-topic` (焦點圖)\n",
    "        for item in soup.select('div.c1 h2 a, div.focus-topic a'):\n",
    "            try:\n",
    "                title = item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                if title and url and 'ettoday.net' in url and '/events/' not in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'ETtoday'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 ETtoday Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (H): 更新 L1 選擇器 (首頁-即時新聞) (2025/11/10) ***\n",
    "        # 抓取 `div.part_list_2` (即時新聞列表)\n",
    "        for item in soup.select('div.part_list_2 h3 a'):\n",
    "            try:\n",
    "                title = item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                if title and url and 'ettoday.net' in url and '/events/' not in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'ETtoday'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 ETtoday Level 1 剖析錯誤: {e}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 ETtoday 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 ETtoday 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (8/9) ChinaTimes 中時新聞網 (v13 修復版)\n",
    "#\n",
    "def fetch_chinatimes_headlines():\n",
    "    \"\"\"(8/9) 抓取 ChinaTimes 中時新聞網 頭條\"\"\"\n",
    "    logging.info(\"--- (8/9) 正在抓取 China Times 中時新聞網頭條 ---\")\n",
    "    base_url = 'https://www.chinatimes.com'\n",
    "    \n",
    "    # *** 修正 (S): 根據 11/10 16:20 的 HTML 原始碼，只抓取首頁 ***\n",
    "    soup = get_soup(base_url) \n",
    "    if not soup:\n",
    "        logging.warning(\"🟡 China Times 首頁抓取失敗 (可能發生 403 錯誤)。\")\n",
    "        return []\n",
    "    \n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    try:\n",
    "        # *** 修正 (T): 更新 L3 選擇器 (首頁輪播) (2025/11/10) ***\n",
    "        for item in soup.select('div.focus-gallery div.adaptive-gallery li.item-entry h3.caption-title a'):\n",
    "            try:\n",
    "                title = item.get_text(separator=' ', strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and ('chinatimes.com' in url or 'ctwant.com' in url):\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'CHINATIMES'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 China Times Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (U): 更新 L2 選擇器 (焦點新聞) (2025/11/10) ***\n",
    "        for item in soup.select('section.focus-news ul.vertical-list li h3.title a'):\n",
    "            try:\n",
    "                title = item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'chinatimes.com' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 2, 'scraped_at': scraped_at, 'source': 'CHINATIMES'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 China Times Level 2 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (V): 更新 L1 選擇器 (即時 Tab) (2025/11/10) ***\n",
    "        for item in soup.select('div#news-pane-1-1 ul.vertical-list li h4.title a'):\n",
    "            try:\n",
    "                title = item.get_text(strip=True)\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                if title and url and 'chinatimes.com' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'CHINATIMES'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 China Times Level 1 (realtimenews) 剖析錯誤: {e}\")\n",
    "                \n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 ChinaTimes 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 China Times 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "#\n",
    "# (9/9) LTN 自由時報 (v13 修復版)\n",
    "#\n",
    "def fetch_ltn_headlines():\n",
    "    \"\"\"(9/9) 抓取自由時報 (LTN) 頭條\"\"\"\n",
    "    logging.info(\"--- (9/9) 正在抓取 LTN 自由時報頭條 ---\")\n",
    "    base_url = 'https://news.ltn.com.tw'\n",
    "    headlines = []\n",
    "    scraped_at = get_current_utc_time()\n",
    "\n",
    "    try:\n",
    "        # *** 修正 (W): 根據 11/10 16:20 的 HTML 原始碼，L1, L2, L3 皆可從首頁抓取 ***\n",
    "        # 移除對 /list/breakingnews 的額外請求，只抓取首頁\n",
    "        # LTN 首頁的 base href 是 https://www.ltn.com.tw/\n",
    "        soup = get_soup('https://www.ltn.com.tw/') \n",
    "        if not soup:\n",
    "            logging.warning(\"🟡 LTN 首頁抓取失敗 (可能發生 403 錯誤)。\")\n",
    "            return []\n",
    "\n",
    "        # *** 修正 (X): 更新 L3 選擇器 (首頁大圖) (2025/11/10) ***\n",
    "        for item in soup.select('div#ltn_focus a.swiper-slide'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                # 排除內廣 (L1ad)\n",
    "                if title and url and 'ltn.com.tw' in url and not 'pv6.ltn.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 3, 'scraped_at': scraped_at, 'source': 'LTN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 LTN Level 3 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (Y): 更新 L2 選擇器 (編輯精選) (2025/11/10) ***\n",
    "        for item in soup.select('div.news10 ul.content_list li a'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                # 排除內廣 (L1ad)\n",
    "                if title and url and 'ltn.com.tw' in url and not 'pv6.ltn.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 2, 'scraped_at': scraped_at, 'source': 'LTN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 LTN Level 2 剖析錯誤: {e}\")\n",
    "\n",
    "        # *** 修正 (Z): 更新 L1 選擇器 (即時清單) (2025/11/10) ***\n",
    "        # (原 L1 抓取 /list/breakingnews 頁面，現改為抓取首頁的即時清單)\n",
    "        for item in soup.select('div.breakingnews[data-desc=\"即時清單\"] ul.content_list li a'):\n",
    "            try:\n",
    "                title = item.get('title')\n",
    "                if not title:\n",
    "                    # 備用方案：尋找 h3 標籤\n",
    "                    h3_tag = item.find('h3')\n",
    "                    if h3_tag:\n",
    "                        title = h3_tag.get_text(strip=True)\n",
    "                \n",
    "                url = normalize_url(base_url, item.get('href'))\n",
    "                \n",
    "                if title and url and 'ltn.com.tw' in url and not 'pv6.ltn.com.tw' in url:\n",
    "                    headlines.append({'url': url, 'title': title, 'headline_level': 1, 'scraped_at': scraped_at, 'source': 'LTN'})\n",
    "            except Exception as e:\n",
    "                logging.warning(f\"🟡 LTN Level 1 剖析錯誤: {e}\")\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(f\"🔥 LTN 爬蟲執行時發生未預期錯誤: {e}\")\n",
    "\n",
    "    logging.info(f\"💡 LTN 抓取到 {len(headlines)} 筆頭條\")\n",
    "    return headlines\n",
    "\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 5: Part 1 執行函式 (v14 全新資料集版)\n",
    "# ===============================================================\n",
    "\n",
    "def run_part1_headline_fetch():\n",
    "    \"\"\"\n",
    "    執行 Part 1：抓取所有媒體的頭條，並找出新 URL。\n",
    "    v14 版：會強制清空舊快取，抓取所有當前新聞。\n",
    "    \"\"\"\n",
    "    logging.info(\"--- Part 1 開始：抓取所有媒體頭條 ---\")\n",
    "    \n",
    "    # 讀取舊的 URL Set\n",
    "    # *** v14 變更：強制使用空的 Set，忽略舊的 JSON 快取 ***\n",
    "    old_urls_set = set()\n",
    "    logging.info(f\"v14 全新資料集模式：已清空舊快取，將重新抓取所有可見頭條。\")\n",
    "    \n",
    "    # 存放所有新抓到的頭條 (List of Dicts)\n",
    "    all_new_headlines = []\n",
    "    # 存放所有這次抓到的 URL (用來更新 JSON)\n",
    "    current_urls_set = set()\n",
    "\n",
    "    # 依序執行各家爬蟲\n",
    "    # 順序依照您先前的重要性排序\n",
    "    fetch_functions = [\n",
    "        fetch_cna_headlines,\n",
    "        fetch_udn_headlines,\n",
    "        fetch_setn_headlines,\n",
    "        fetch_tvbs_headlines,\n",
    "        fetch_ebc_headlines,\n",
    "        fetch_nownews_headlines,\n",
    "        fetch_ettoday_headlines,\n",
    "        fetch_ltn_headlines,\n",
    "        fetch_chinatimes_headlines\n",
    "    ]\n",
    "\n",
    "    for func in fetch_functions:\n",
    "        try:\n",
    "            headlines = func() # 執行爬蟲，回傳 List[Dict]\n",
    "            \n",
    "            # 找出「新的」頭條\n",
    "            new_count = 0\n",
    "            for h in headlines:\n",
    "                url = h['url']\n",
    "                current_urls_set.add(url) # 加入「本次」抓取的 Set\n",
    "                \n",
    "                if url not in old_urls_set:\n",
    "                    all_new_headlines.append(h) # 這是一筆全新的 URL\n",
    "                    new_count += 1\n",
    "                    \n",
    "            logging.info(f\"✓ {func.__name__} 完成，發現 {new_count} 筆新頭條。\")\n",
    "            \n",
    "        except Exception as e:\n",
    "            logging.error(f\"🔥 執行 {func.__name__} 時發生嚴重錯誤: {e}\")\n",
    "            \n",
    "        time.sleep(1) # 禮貌性延遲 1 秒\n",
    "\n",
    "    # 合併「舊的」URL Set 和「本次」抓取的 URL Set\n",
    "    # 在 v14 中，old_urls_set 永遠是空的，所以 combined_urls_set == current_urls_set\n",
    "    combined_urls_set = old_urls_set.union(current_urls_set)\n",
    "    \n",
    "    # 儲存合併後的完整 URL Set 回 JSON\n",
    "    # *** v14 變更：會寫入到 news_dataset_cache.json ***\n",
    "    save_headlines_to_json(combined_urls_set, TEMP_JSON_FILENAME)\n",
    "\n",
    "    logging.info(\"--- Part 1 完成 ---\")\n",
    "    logging.info(f\"總共發現 {len(all_new_headlines)} 筆全新 URL (來自9家媒體)。\")\n",
    "    \n",
    "    return all_new_headlines # 回傳「全新」的頭條列表，給 Part 2 使用\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 6: Part 2 核心功能 (抓取內文並建立快照) (v13 版)\n",
    "# ===============================================================\n",
    "\n",
    "def get_article_content(url, source):\n",
    "    \"\"\"\n",
    "    根據不同媒體來源，抓取文章內文。\n",
    "    \"\"\"\n",
    "    soup = get_soup(url)\n",
    "    if not soup:\n",
    "        return f\"錯誤：抓取失敗 {url}\"\n",
    "\n",
    "    content = \"\"\n",
    "    selectors = []\n",
    "\n",
    "    try:\n",
    "        if source == 'CNA':\n",
    "            selectors = ['div.article-content p', 'div.central-text p']\n",
    "        elif source == 'UDN':\n",
    "            selectors = ['section.article-content__editor p']\n",
    "        elif source == 'SETN':\n",
    "            selectors = ['div#Content1 p']\n",
    "        elif source == 'TVBS':\n",
    "            selectors = ['div.article_content p', 'div.article_content div']\n",
    "        elif source == 'EBC':\n",
    "            selectors = ['div.raw-style p']\n",
    "        elif source == 'NOWnews':\n",
    "            selectors = ['article.article-content p']\n",
    "        elif source == 'ETtoday':\n",
    "            selectors = ['div.story p']\n",
    "        elif source == 'LTN':\n",
    "            selectors = ['div.text p']\n",
    "        elif source == 'CHINATIMES':\n",
    "            selectors = ['div.article-body p']\n",
    "        \n",
    "        elements = soup.select(', '.join(selectors))\n",
    "        \n",
    "        if not elements:\n",
    "            # 如果主要選擇器抓不到，嘗試通用的 <p> 標籤\n",
    "            elements = soup.find_all('p')\n",
    "            if not elements:\n",
    "                 return f\"錯誤：找不到任何 <p> 標籤 {url}\"\n",
    "                 \n",
    "        for el in elements:\n",
    "            # 排除廣告或不相關的 <p>\n",
    "            text = el.get_text(strip=True)\n",
    "            if text and '延伸閱讀' not in text and '記者' not in text[:5] and '▲' not in text[:5]:\n",
    "                content += text + \"\\n\"\n",
    "        \n",
    "        return content if content else f\"錯誤：內容為空 {url}\"\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.warning(f\"🟡 剖析內文失敗: {url} ({e})\")\n",
    "        return f\"錯誤：剖析失敗 {url} ({e})\"\n",
    "\n",
    "def create_snapshot_data(headline_list):\n",
    "    \"\"\"\n",
    "    接收 Part 1 產出的「新頭條列表」，逐一抓取內文，\n",
    "    並轉換為準備寫入 CSV 的 DataFrame。\n",
    "    \"\"\"\n",
    "    snapshot_data = [] # 存放所有要寫入 CSV 的資料 (List of Dicts)\n",
    "    \n",
    "    if not headline_list:\n",
    "        return pd.DataFrame(columns=SNAPSHOT_COLUMNS) # 回傳空的 DF\n",
    "\n",
    "    total = len(headline_list)\n",
    "    logging.info(f\"--- Part 2 開始：準備抓取 {total} 筆新文章內文 ---\")\n",
    "\n",
    "    for i, headline in enumerate(headline_list):\n",
    "        url = headline['url']\n",
    "        source = headline['source']\n",
    "        \n",
    "        logging.info(f\"  ({i+1}/{total}) 正在抓取 [{source}] {url}...\")\n",
    "        \n",
    "        content = get_article_content(url, source)\n",
    "        \n",
    "        # 產生 URL Hash (您 CSV 中的 url_hash)\n",
    "        # 這裡我們用簡單的 hash() 轉字串\n",
    "        url_hash = str(hash(url))\n",
    "\n",
    "        # 建立一筆快照資料 (7個欄位)\n",
    "        snapshot_entry = {\n",
    "            'url': url,\n",
    "            'title': headline['title'],\n",
    "            'headline_level': headline['headline_level'],\n",
    "            'snapshot_at': headline['scraped_at'],\n",
    "            'full_content': content,\n",
    "            'source': source,\n",
    "            'url_hash': url_hash\n",
    "        }\n",
    "        snapshot_data.append(snapshot_entry)\n",
    "        \n",
    "        time.sleep(0.5) # 禮貌性延遲 0.5 秒\n",
    "\n",
    "    logging.info(f\"✓ Part 2 內文抓取完成。\")\n",
    "    \n",
    "    # 轉換為 DataFrame\n",
    "    df = pd.DataFrame(snapshot_data, columns=SNAPSHOT_COLUMNS)\n",
    "    return df\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 7: Part 2 執行函式 (v14 全新資料集版)\n",
    "# ===============================================================\n",
    "\n",
    "def run_part2_scrape_and_append():\n",
    "    \"\"\"\n",
    "    執行 Part 2：\n",
    "    1. 執行 Part 1 取得「新」聞列表 (v14 版會抓取所有新聞)\n",
    "    2. 抓取「新」聞的內文\n",
    "    3. 將這些「新」聞寫入到 `news_dataset.csv`\n",
    "    \"\"\"\n",
    "    \n",
    "    # 1. 執行 Part 1\n",
    "    # new_headlines_list 是一個 List[Dict]，包含所有被抓到的 URL\n",
    "    new_headlines_list = run_part1_headline_fetch()\n",
    "    \n",
    "    if not new_headlines_list:\n",
    "        logging.info(\"👍 Part 2 完成：沒有發現需要抓取內文的新文章。\")\n",
    "        return\n",
    "\n",
    "    # 2. 抓取新文章內文\n",
    "    new_df = create_snapshot_data(new_headlines_list)\n",
    "    new_snapshot_data = new_df.to_dict('records') # 轉換回 List[Dict]\n",
    "\n",
    "    # 3. 寫入 (Write) 到 CSV\n",
    "    # *** v14 變更：DB_FILENAME 已被改為 'news_dataset.csv' ***\n",
    "    if new_snapshot_data:\n",
    "        try:\n",
    "            # 檢查 DB_FILENAME 是否已存在\n",
    "            file_exists = os.path.exists(DB_FILENAME)\n",
    "            \n",
    "            # *** v14 變更：第一次執行 'news_dataset.csv' 時，file_exists 會是 False ***\n",
    "            if not file_exists:\n",
    "                logging.warning(f\"🟡 {DB_FILENAME} 不存在。將自動建立新檔案並寫入 7 欄位標頭。\")\n",
    "            else:\n",
    "                logging.warning(f\"🟡 {DB_FILENAME} 已存在。本次抓取的資料將「附加」到現有檔案中。\")\n",
    "                logging.warning(f\"   如需「完全重新」的資料集，請先手動刪除 {DB_FILENAME} 和 {TEMP_JSON_FILENAME}。\")\n",
    "\n",
    "            \n",
    "            # *** 使用 'a' (append) 模式 ***\n",
    "            # 這樣設計可確保：\n",
    "            # 1. 如果 news_dataset.csv 不存在 -> 建立新檔 + 寫入標頭 + 寫入資料 (您要的)\n",
    "            # 2. 如果 news_dataset.csv 已存在 -> 附加資料 (Crontab 下次執行時)\n",
    "            new_df.to_csv(\n",
    "                DB_FILENAME, \n",
    "                mode='a',                 # 'a' 代表 append (附加)\n",
    "                header=not file_exists,   # 只有在檔案不存在時才寫入 header\n",
    "                index=False, \n",
    "                encoding='utf-8-sig'\n",
    "            )\n",
    "            \n",
    "            logging.info(f\"✅ Part 2 完成：成功抓取並寫入 {len(new_snapshot_data)} 筆新快照到 {DB_FILENAME}\")\n",
    "            \n",
    "        except IOError as e:\n",
    "            logging.error(f\"🔥 Part 2 錯誤：儲存到 {DB_FILENAME} 失敗: {e}\")\n",
    "        except Exception as e:\n",
    "            logging.error(f\"🔥 Part 2 儲存時發生未知錯誤: {e}\")\n",
    "    else:\n",
    "        logging.warning(\"👍 Part 2 完成：本次快照未成功抓取到任何新文章。\")\n",
    "\n",
    "# ===============================================================\n",
    "# Cell 8: 完整執行所有爬蟲任務\n",
    "# ===============================================================\n",
    "\n",
    "def main_execution():\n",
    "    \"\"\"\n",
    "    依序執行所有爬蟲步驟\n",
    "    \"\"\"\n",
    "    \n",
    "    start_time = time.time()\n",
    "    logging.info(f\"======= 爬蟲任務開始於 {get_current_utc_time()} =======\")\n",
    "    \n",
    "    # 步驟一 & 步驟二：\n",
    "    # run_part2_scrape_and_append() 會自動呼叫 Part 1，\n",
    "    # 然後抓取新文章內文，最後寫入到 news_dataset.csv\n",
    "    run_part2_scrape_and_append()\n",
    "    \n",
    "    # 步驟三：(已移除) \n",
    "    \n",
    "    end_time = time.time()\n",
    "    sources = \"CNA, UDN, SETN, TVBS, EBC, NOWnews, ETtoday, LTN, ChinaTimes\"\n",
    "    logging.info(f\"\\n======= 爬蟲任務完成 ({sources})，總耗時: {end_time - start_time:.2f} 秒 =======\")\n",
    "\n",
    "# 確保這個 .py 檔案被直接執行時，才會觸發 main_execution()\n",
    "if __name__ == \"__main__\":\n",
    "    # 立即執行主程式\n",
    "    main_execution()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2ed3f323-cfaf-4d52-9b60-2d50d3b9f068",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
