{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a9e6b785-dbfc-4334-b3e4-65cb7c4bf022",
   "metadata": {},
   "outputs": [],
   "source": [
    "#!/usr/bin/env python3\n",
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "import sys\n",
    "import logging\n",
    "import os\n",
    "import random\n",
    "import time\n",
    "import re\n",
    "import math\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from datetime import datetime, timedelta\n",
    "from bs4 import BeautifulSoup\n",
    "from dateutil import parser as date_parser\n",
    "\n",
    "# --- Selenium ---\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.action_chains import ActionChains\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "from selenium.common.exceptions import TimeoutException, WebDriverException\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "# --- Requests ---\n",
    "import requests\n",
    "import warnings\n",
    "from urllib3.exceptions import InsecureRequestWarning\n",
    "\n",
    "warnings.simplefilter('ignore', InsecureRequestWarning)\n",
    "\n",
    "# ===============================================================\n",
    "#  1. 全域設定 (Global Settings)\n",
    "# ===============================================================\n",
    "\n",
    "try:\n",
    "    BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n",
    "except NameError:\n",
    "    BASE_DIR = os.getcwd()\n",
    "\n",
    "# 資料庫路徑\n",
    "DATA_FILENAME = os.path.join(BASE_DIR, 'News.csv')\n",
    "LOG_FILENAME = os.path.join(BASE_DIR, 'scraper_final.log')\n",
    "\n",
    "# 標準欄位\n",
    "V5_COLUMNS = ['url', 'media', 'category', 'publish_time', 'title', 'content', 'fetch_time', 'label']\n",
    "\n",
    "# 抓取目標數量\n",
    "LIMIT_L1 = 50\n",
    "LIMIT_L0 = 75\n",
    "\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format='%(asctime)s - %(levelname)s - %(message)s',\n",
    "    handlers=[\n",
    "        logging.FileHandler(LOG_FILENAME, encoding='utf-8', mode='a'),\n",
    "        logging.StreamHandler(sys.stdout)\n",
    "    ]\n",
    ")\n",
    "\n",
    "HEADERS = {\n",
    "    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',\n",
    "    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',\n",
    "    'Referer': 'https://www.google.com/'\n",
    "}\n",
    "\n",
    "# ===============================================================\n",
    "#  2. 媒體設定檔 (Media Configs)\n",
    "# ===============================================================\n",
    "\n",
    "MEDIA_CONFIGS = [\n",
    "    {\n",
    "        'name': 'SETN',\n",
    "        'hot_url': 'https://www.setn.com/ViewAll.aspx?PageGroupID=6',\n",
    "        'latest_url': 'https://www.setn.com/ViewAll.aspx',\n",
    "        'base_url': 'https://www.setn.com',\n",
    "        'hot_selector': ['h3.view-li-title a', 'div.news-list-group a.gt', 'div.col-sm-12 h3 a'],\n",
    "        'latest_selector': ['h3.view-li-title a', 'div.col-sm-12 > a']\n",
    "    },\n",
    "    {\n",
    "        'name': 'TVBS',\n",
    "        'hot_url': 'https://news.tvbs.com.tw/hot',\n",
    "        'latest_url': 'https://news.tvbs.com.tw/realtime',\n",
    "        'base_url': 'https://news.tvbs.com.tw',\n",
    "        'hot_selector': ['div.news_list li a', 'div.list li a'],\n",
    "        'latest_selector': ['div.news_list li a']\n",
    "    },\n",
    "    {\n",
    "        'name': 'ETtoday',\n",
    "        'hot_url': 'https://www.ettoday.net/news/hot-news.htm',\n",
    "        'latest_url': 'https://www.ettoday.net/news/news-list.htm',\n",
    "        'base_url': 'https://www.ettoday.net',\n",
    "        'hot_selector': ['div.part_list_2 h3 a', 'div.block_content h3 a'],\n",
    "        'latest_selector': ['div.part_list_2 h3 a']\n",
    "    },\n",
    "    {\n",
    "        'name': 'LTN',\n",
    "        'hot_url': 'https://news.ltn.com.tw/list/breakingnews/popular',\n",
    "        'latest_url': 'https://news.ltn.com.tw/list/breakingnews',\n",
    "        'base_url': 'https://news.ltn.com.tw',\n",
    "        # 廣域容器掃描 (之後再過濾網址)\n",
    "        'hot_selector': ['div.whitecon a', 'ul.list a', 'div.boxTitle a', 'a.tit'],\n",
    "        'latest_selector': ['div.whitecon ul.list li a', 'div.whitecon a', 'ul.list a']\n",
    "    },\n",
    "    {\n",
    "        'name': 'ChinaTimes',\n",
    "        'hot_url': 'https://www.chinatimes.com/hotnews/?chdtv',\n",
    "        'latest_url': 'https://www.chinatimes.com/realtimenews/?chdtv',\n",
    "        'base_url': 'https://www.chinatimes.com',\n",
    "        'hot_selector': ['section.hot-news li h3.title a', 'ul.vertical-list li h3 a'],\n",
    "        'latest_selector': ['section.article-list li h3.title a']\n",
    "    },\n",
    "    {\n",
    "        'name': 'UDN',\n",
    "        'hot_url': 'https://udn.com/rank/pv/2',\n",
    "        'latest_url': 'https://udn.com/news/breaknews/1',\n",
    "        'base_url': 'https://udn.com',\n",
    "        'hot_selector': ['div.story-list__text h2 a', 'section.rank-list h3 a'],\n",
    "        'latest_selector': ['div.story-list__text h2 a']\n",
    "    }\n",
    "]\n",
    "\n",
    "# 全子網域內文選擇器矩陣\n",
    "CONTENT_SELECTORS = [\n",
    "    'div.article-content',          # 通用\n",
    "    'div.story',                    # ETtoday\n",
    "    'div.article-body',             # ChinaTimes\n",
    "    'div[itemprop=\"articleBody\"]',  # LTN 主站\n",
    "    'div.text',                     # LTN 財經/娛樂/通用\n",
    "    'div.news_content',             # LTN 體育\n",
    "    'div.box_data',                 # LTN 汽車/其他\n",
    "    'div.content',                  # 子版通用\n",
    "    'div#Content1',                 # SETN 主站\n",
    "    'div.article_content',          # TVBS\n",
    "    'section.article-content__editor', # UDN\n",
    "    'div.p-note',\n",
    "    'div.fncnews-content',\n",
    "    'div.post-content',\n",
    "    'article'                       # 終極備案\n",
    "]\n",
    "\n",
    "# ===============================================================\n",
    "#  3. 資料清洗與中文優化模組 (V13.1)\n",
    "# ===============================================================\n",
    "\n",
    "# 翻譯字典 (最後一道防線)\n",
    "CATEGORY_MAP = {\n",
    "    'politics': '政治', 'society': '社會', 'life': '生活', 'world': '國際',\n",
    "    'local': '地方', 'novelty': '搜奇', 'business': '財經', 'finance': '財經',\n",
    "    'ec': '財經', 'sports': '體育', 'entertainment': '娛樂', 'ent': '娛樂',\n",
    "    'star': '娛樂', 'health': '健康', 'supplement': '副刊', 'opinion': '言論',\n",
    "    'talk': '言論', 'focus': '焦點', '3c': '3C科技', 'auto': '汽車', 'fashion': '時尚'\n",
    "}\n",
    "\n",
    "def clean_category(cat_str):\n",
    "    \"\"\"清洗並翻譯分類\"\"\"\n",
    "    if not cat_str: return \"即時\"\n",
    "    \n",
    "    cat_str = str(cat_str).strip()\n",
    "    \n",
    "    # 處理麵包屑格式 \"首頁 > 政治\"\n",
    "    if '>' in cat_str: \n",
    "        parts = cat_str.split('>')\n",
    "        if len(parts) >= 2:\n",
    "            candidate = parts[-1].strip()\n",
    "            # 若最後一段太長(>10字)可能是標題，改取上一層\n",
    "            if len(candidate) > 10:\n",
    "                cat_str = parts[-2].strip()\n",
    "            else:\n",
    "                cat_str = candidate\n",
    "        else:\n",
    "            cat_str = parts[-1].strip()\n",
    "            \n",
    "    elif '/' in cat_str and len(cat_str) < 20: \n",
    "        cat_str = cat_str.split('/')[-1].strip()\n",
    "\n",
    "    # 去除多餘字樣\n",
    "    cat_str = cat_str.replace(\"自由時報\", \"\").replace(\"LTN\", \"\").strip()\n",
    "\n",
    "    # 查表翻譯 (若仍為英文)\n",
    "    lower_cat = cat_str.lower()\n",
    "    if lower_cat in CATEGORY_MAP:\n",
    "        return CATEGORY_MAP[lower_cat]\n",
    "        \n",
    "    return cat_str\n",
    "\n",
    "def format_time_strict(time_str):\n",
    "    now = datetime.now()\n",
    "    if not time_str or str(time_str).lower() in ['nan', 'n/a', 'none', '']:\n",
    "        return now.strftime(\"%Y/%-m/%-d %-I:%M:%S %p\")\n",
    "    try:\n",
    "        raw = str(time_str).replace(\"發布時間：\", \"\").replace(\"更新時間：\", \"\").strip()\n",
    "        if \"小時前\" in raw:\n",
    "            hours = int(re.search(r'(\\d+)', raw).group(1))\n",
    "            dt = now - timedelta(hours=hours)\n",
    "        elif \"分鐘前\" in raw:\n",
    "            mins = int(re.search(r'(\\d+)', raw).group(1))\n",
    "            dt = now - timedelta(minutes=mins)\n",
    "        elif \"剛剛\" in raw:\n",
    "            dt = now\n",
    "        else:\n",
    "            dt = date_parser.parse(raw, fuzzy=True)\n",
    "        \n",
    "        hour_12 = int(dt.strftime(\"%I\"))\n",
    "        time_part = f\"{hour_12}:{dt.strftime('%M:%S %p')}\"\n",
    "        return f\"{dt.year}/{dt.month}/{dt.day} {time_part}\"\n",
    "    except:\n",
    "        return now.strftime(\"%Y/%-m/%-d %-I:%M:%S %p\")\n",
    "\n",
    "def parse_html_content(html_text):\n",
    "    soup = BeautifulSoup(html_text, 'lxml')\n",
    "    content = np.nan\n",
    "    \n",
    "    # 1. 內文\n",
    "    for sel in CONTENT_SELECTORS:\n",
    "        elm = soup.select_one(sel)\n",
    "        if elm:\n",
    "            for tag in elm(['script', 'style', 'iframe', 'div.knn_related', 'div.fb-root', 'div.author', 'div.ad', 'div.click_mic', 'p.app_ad']):\n",
    "                tag.decompose()\n",
    "            text = elm.get_text(separator=' ', strip=True)\n",
    "            text = re.sub(r'\\s+', ' ', text)\n",
    "            if len(text) > 30:\n",
    "                content = text\n",
    "                break\n",
    "    \n",
    "    # 2. 分類 (優先抓麵包屑，因為是中文)\n",
    "    category = None\n",
    "    crumbs_selectors = [\n",
    "        'div.guide', 'div.breadcrumbs', 'div.breadcrumb', \n",
    "        'nav[aria-label=\"breadcrumb\"]', 'div.path'\n",
    "    ]\n",
    "    for sel in crumbs_selectors:\n",
    "        crumbs = soup.select_one(sel)\n",
    "        if crumbs:\n",
    "            category = crumbs.get_text(separator=' > ', strip=True)\n",
    "            break\n",
    "    \n",
    "    # 備案：抓 Meta Tag\n",
    "    if not category:\n",
    "        meta_sec = soup.select_one('meta[property=\"article:section\"]')\n",
    "        if meta_sec and meta_sec.get('content'):\n",
    "            category = meta_sec.get('content')\n",
    "    \n",
    "    if not category: category = \"即時\"\n",
    "\n",
    "    # 3. 時間\n",
    "    raw_time = None\n",
    "    time_elm = soup.select_one('meta[property=\"article:published_time\"], meta[name=\"pubdate\"], time, span.time, div.date, div.meta-info time')\n",
    "    if time_elm:\n",
    "        raw_time = time_elm.get('content') if time_elm.has_attr('content') else time_elm.get_text(strip=True)\n",
    "    \n",
    "    return clean_category(category), format_time_strict(raw_time), content\n",
    "\n",
    "# ===============================================================\n",
    "#  4. 爬蟲核心 (HumanNavigator)\n",
    "# ===============================================================\n",
    "\n",
    "class HumanNavigator:\n",
    "    def __init__(self, driver):\n",
    "        self.driver = driver\n",
    "        self.action = ActionChains(driver)\n",
    "\n",
    "    def random_sleep(self, min_s=1.5, max_s=3.0):\n",
    "        time.sleep(random.uniform(min_s, max_s))\n",
    "\n",
    "    def smooth_scroll(self):\n",
    "        try:\n",
    "            current_pos = self.driver.execute_script(\"return window.pageYOffset;\")\n",
    "            target_distance = random.randint(800, 1200)\n",
    "            steps = random.randint(10, 20)\n",
    "            for _ in range(steps):\n",
    "                move = (target_distance / steps) + random.uniform(-5, 5) \n",
    "                current_pos += move\n",
    "                self.driver.execute_script(f\"window.scrollTo(0, {current_pos});\")\n",
    "                time.sleep(0.02)\n",
    "        except: pass\n",
    "\n",
    "    def random_mouse_move(self):\n",
    "        try:\n",
    "            links = self.driver.find_elements(By.TAG_NAME, \"a\")\n",
    "            if len(links) > 0:\n",
    "                target = random.choice(links[:15]) \n",
    "                self.action.move_to_element(target).perform()\n",
    "        except: pass\n",
    "\n",
    "class NewsSpider:\n",
    "    def __init__(self):\n",
    "        self.options = Options()\n",
    "        self.options.add_argument(\"--headless\") # 正式跑時可開啟 headless\n",
    "        # self.options.add_argument(\"--start-maximized\") # 測試時可開啟視窗\n",
    "        self.options.add_argument(\"--disable-gpu\")\n",
    "        self.options.add_argument(\"--no-sandbox\")\n",
    "        self.options.add_argument(\"--window-size=1920,1080\")\n",
    "        self.options.add_argument(f\"user-agent={HEADERS['User-Agent']}\")\n",
    "        self.options.add_argument(\"--disable-blink-features=AutomationControlled\")\n",
    "        self.options.add_experimental_option(\"excludeSwitches\", [\"enable-automation\"])\n",
    "        self.options.add_experimental_option('useAutomationExtension', False)\n",
    "        \n",
    "        prefs = {\"profile.managed_default_content_settings.images\": 2}\n",
    "        self.options.add_experimental_option(\"prefs\", prefs)\n",
    "        \n",
    "        self.driver = None\n",
    "        self.human = None\n",
    "        self.existing_data = self._get_existing_data()\n",
    "\n",
    "    def _get_existing_data(self):\n",
    "        existing = {}\n",
    "        if os.path.exists(DATA_FILENAME):\n",
    "            try:\n",
    "                df = pd.read_csv(DATA_FILENAME)\n",
    "                if 'url' in df.columns and 'label' in df.columns:\n",
    "                    for idx, row in df.iterrows():\n",
    "                        existing[str(row['url'])] = row['label']\n",
    "            except: pass\n",
    "        return existing\n",
    "\n",
    "    def start(self):\n",
    "        # 🔥 [修正重點] 強制指定與您 Chrome 143 匹配的 Driver 版本\n",
    "        # 143.0.7499.169 是目前 WD Manager 支援的最接近版本\n",
    "        service = Service(ChromeDriverManager(driver_version=\"143.0.7499.169\").install())\n",
    "        \n",
    "        self.driver = webdriver.Chrome(service=service, options=self.options)\n",
    "        self.driver.set_page_load_timeout(45)\n",
    "        self.driver.execute_script(\"Object.defineProperty(navigator, 'webdriver', {get: () => undefined})\")\n",
    "        self.human = HumanNavigator(self.driver)\n",
    "\n",
    "    def stop(self):\n",
    "        if self.driver:\n",
    "            try: self.driver.quit()\n",
    "            except: pass\n",
    "            self.driver = None\n",
    "\n",
    "    def fetch_content_smart(self, url):\n",
    "        try:\n",
    "            res = requests.get(url, headers=HEADERS, timeout=6, verify=False)\n",
    "            if res.status_code == 200:\n",
    "                cat, t, c = parse_html_content(res.text)\n",
    "                if isinstance(c, str): return cat, t, c\n",
    "        except: pass\n",
    "\n",
    "        try:\n",
    "            self.driver.execute_script(\"window.open('');\")\n",
    "            self.driver.switch_to.window(self.driver.window_handles[-1])\n",
    "            try:\n",
    "                self.driver.get(url)\n",
    "            except TimeoutException:\n",
    "                self.driver.execute_script(\"window.stop();\")\n",
    "            \n",
    "            self.human.random_sleep(1.0, 2.0)\n",
    "            html = self.driver.page_source\n",
    "            self.driver.close()\n",
    "            self.driver.switch_to.window(self.driver.window_handles[0])\n",
    "            return parse_html_content(html)\n",
    "        except:\n",
    "            try:\n",
    "                if len(self.driver.window_handles) > 1:\n",
    "                    self.driver.close()\n",
    "                    self.driver.switch_to.window(self.driver.window_handles[0])\n",
    "            except: pass\n",
    "        return \"即時\", format_time_strict(None), np.nan\n",
    "\n",
    "    def crawl_task(self, site_config, label, limit):\n",
    "        url = site_config['hot_url'] if label == 1 else site_config['latest_url']\n",
    "        selectors = site_config['hot_selector'] if label == 1 else site_config['latest_selector']\n",
    "        site_name = site_config['name']\n",
    "\n",
    "        logging.info(f\"      L{label} 任務啟動 (目標: {limit} 筆)...\")\n",
    "        try:\n",
    "            try:\n",
    "                self.driver.get(url)\n",
    "                # 增加 Log 確認是否成功進入頁面\n",
    "                logging.info(f\"      🔍 已訪問: {url} | Title: {self.driver.title}\")\n",
    "                \n",
    "                try:\n",
    "                    WebDriverWait(self.driver, 15).until(EC.presence_of_element_located((By.TAG_NAME, \"body\")))\n",
    "                    if site_name == 'LTN': time.sleep(5) \n",
    "                    else: self.human.random_sleep(2, 4)\n",
    "                except: pass\n",
    "            except TimeoutException:\n",
    "                logging.warning(\"      ⚠️ 列表載入超時，強制停止...\")\n",
    "                self.driver.execute_script(\"window.stop();\")\n",
    "\n",
    "            collected = []\n",
    "            seen_links = set()\n",
    "            \n",
    "            scroll_target = int((limit / 8) * 1.5) + 3\n",
    "            for _ in range(scroll_target):\n",
    "                self.human.smooth_scroll()\n",
    "                self.human.random_mouse_move()\n",
    "                self.human.random_sleep(1.0, 1.5)\n",
    "                soup = BeautifulSoup(self.driver.page_source, 'lxml')\n",
    "                found_count = 0\n",
    "                for sel in selectors: found_count += len(soup.select(sel))\n",
    "                if found_count >= limit * 1.2: break\n",
    "            \n",
    "            soup = BeautifulSoup(self.driver.page_source, 'lxml')\n",
    "            elements = []\n",
    "            for sel in selectors:\n",
    "                found = soup.select(sel)\n",
    "                if found: elements.extend(found)\n",
    "\n",
    "            logging.info(f\"      -> 掃描到 {len(elements)} 個連結...\")\n",
    "\n",
    "            for item in elements:\n",
    "                if len(collected) >= limit: break\n",
    "                try:\n",
    "                    link = item.get('href')\n",
    "                    # LTN 過濾器\n",
    "                    if site_name == 'LTN':\n",
    "                        if not link: continue\n",
    "                        if not any(x in link for x in ['/news/', '/article/', 'sports', 'ent', 'ec', 'auto']): continue\n",
    "                    \n",
    "                    title = item.get('title') or item.get_text(strip=True)\n",
    "                    if not link or not title or len(title) < 4: continue\n",
    "                    \n",
    "                    if link.startswith('/'):\n",
    "                        base = site_config['base_url']\n",
    "                        full_url = base.rstrip('/') + '/' + link.lstrip('/')\n",
    "                    elif link.startswith('http'):\n",
    "                        full_url = link\n",
    "                    else: continue\n",
    "                    \n",
    "                    if 'setn.com' in full_url and 'NewsID=' in full_url: clean_url = full_url \n",
    "                    elif 'udn.com' in full_url and 'story/' in full_url: clean_url = full_url \n",
    "                    else: clean_url = full_url.split('?')[0]\n",
    "\n",
    "                    if clean_url in seen_links: continue\n",
    "                    seen_links.add(clean_url)\n",
    "\n",
    "                    # 智慧去重與升級\n",
    "                    is_in_db = clean_url in self.existing_data\n",
    "                    db_label = self.existing_data.get(clean_url, -1)\n",
    "\n",
    "                    if is_in_db:\n",
    "                        if label == 1 and db_label == 0:\n",
    "                            logging.info(f\"         [Upgrade] 發現 L0->L1 潛力股: {title[:8]}\")\n",
    "                        elif label == 1 and db_label == 1: continue\n",
    "                        elif label == 0: continue\n",
    "\n",
    "                    cat, t_str, content = self.fetch_content_smart(full_url)\n",
    "                    if not isinstance(content, str) or len(content) < 30: continue \n",
    "\n",
    "                    fetch_time = datetime.now().strftime(\"%Y/%-m/%-d %-I:%M:%S %p\")\n",
    "                    \n",
    "                    collected.append({\n",
    "                        'url': full_url,\n",
    "                        'media': site_name,\n",
    "                        'category': cat, # V13.1 Native Chinese\n",
    "                        'publish_time': t_str,\n",
    "                        'title': title,\n",
    "                        'content': content,\n",
    "                        'fetch_time': fetch_time,\n",
    "                        'label': label\n",
    "                    })\n",
    "                    \n",
    "                    print(f\"         [L{label}] {title[:8]}... (OK) - {cat}\")\n",
    "                    time.sleep(random.uniform(1.5, 3.0))\n",
    "\n",
    "                except Exception: continue\n",
    "            \n",
    "            return collected\n",
    "\n",
    "        except Exception as e:\n",
    "            logging.error(f\"      🔥 任務錯誤: {e}\")\n",
    "            return []\n",
    "\n",
    "# ===============================================================\n",
    "#  5. 主程式\n",
    "# ===============================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # 建立一個全域的 Spider (瀏覽器只開一次)\n",
    "    spider = NewsSpider()\n",
    "    \n",
    "    try:\n",
    "        logging.info(\"🚀 啟動爬蟲任務...\")\n",
    "        \n",
    "        for site_config in MEDIA_CONFIGS:\n",
    "            site_name = site_config['name']\n",
    "            logging.info(f\"--- 處理媒體: {site_name} ---\")\n",
    "            \n",
    "            try:\n",
    "                all_data = []\n",
    "                \n",
    "                # 1. 抓取 L1 (熱門)\n",
    "                logging.info(f\"      L1 任務啟動 (目標: {LIMIT_L1} 筆)...\")\n",
    "                l1_data = spider.crawl_task(site_config, label=1, limit=LIMIT_L1)\n",
    "                all_data.extend(l1_data)\n",
    "                logging.info(f\"      ✅ {site_name} L1 完成: {len(l1_data)} 筆\")\n",
    "                \n",
    "                # 休息一下，避免被網站發現連續請求太快\n",
    "                spider.human.random_sleep(2, 4)\n",
    "                \n",
    "                # 2. 抓取 L0 (一般)\n",
    "                logging.info(f\"      L0 任務啟動 (目標: {LIMIT_L0} 筆)...\")\n",
    "                l0_data = spider.crawl_task(site_config, label=0, limit=LIMIT_L0)\n",
    "                all_data.extend(l0_data)\n",
    "                logging.info(f\"      ✅ {site_name} L0 完成: {len(l0_data)} 筆\")\n",
    "                \n",
    "                # 存檔\n",
    "                if all_data:\n",
    "                    df = pd.DataFrame(all_data)\n",
    "                    for col in V5_COLUMNS:\n",
    "                        if col not in df.columns: df[col] = np.nan\n",
    "                    df = df[V5_COLUMNS]\n",
    "                    \n",
    "                    header = not os.path.exists(DATA_FILENAME)\n",
    "                    df.to_csv(DATA_FILENAME, mode='a', header=header, index=False, encoding='utf-8-sig')\n",
    "                    logging.info(f\"      💾 {site_name} 數據已存檔\")\n",
    "\n",
    "            except Exception as e:\n",
    "                logging.error(f\"   🔥 {site_name} 單一媒體處理錯誤: {e}\")\n",
    "                # 如果瀏覽器掛了，嘗試重啟\n",
    "                try:\n",
    "                    spider.stop()\n",
    "                    spider = NewsSpider() \n",
    "                except:\n",
    "                    pass\n",
    "\n",
    "            logging.info(f\"   💤 媒體間隔休息 5 秒...\")\n",
    "            time.sleep(5)\n",
    "\n",
    "    except KeyboardInterrupt:\n",
    "        logging.info(\"🛑 使用者手動停止\")\n",
    "    \n",
    "    finally:\n",
    "        # 最後才關閉瀏覽器\n",
    "        spider.stop()\n",
    "        logging.info(\"🔚 爬蟲結束，瀏覽器已關閉\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d4e8ab4-46ad-4269-94ab-6dcdde6fc727",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
