{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4963e785-e663-41c5-ac2a-0664842734c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in /opt/anaconda3/lib/python3.13/site-packages (1.45.1)\n",
      "Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.2.5)\n",
      "Requirement already satisfied: altair<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: packaging<25,>=20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (11.1.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow>=7.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (21.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (9.0.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in /opt/anaconda3/lib/python3.13/site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: jinja2 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (4.23.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in /opt/anaconda3/lib/python3.13/site-packages (from altair<6,>=4.0->streamlit) (1.31.0)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)\n",
      "Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests<3,>=2.27->streamlit) (2025.10.5)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.3.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.13/site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install streamlit pandas numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "6559d3e1-3e1d-4b80-be05-d13fb74164f1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-12-18 16:49:40.772 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.772 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.814 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/anaconda3/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-12-18 16:49:40.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.830 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.831 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.833 Session state does not function when running a script without `streamlit run`\n",
      "2025-12-18 16:49:40.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.833 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.834 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.836 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-12-18 16:49:40.838 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import time\n",
    "import re\n",
    "\n",
    "# ==========================================\n",
    "# 1. 頁面設定 (Page Config)\n",
    "# ==========================================\n",
    "st.set_page_config(\n",
    "    page_title=\"AI 總編輯 - 新聞熱度預測\",\n",
    "    page_icon=\"📰\",\n",
    "    layout=\"centered\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# 自訂 CSS 美化\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .big-font { font-size:30px !important; font-weight: bold; color: #FF4B4B; }\n",
    "    .stButton>button { width: 100%; border-radius: 20px; }\n",
    "    .metric-card { background-color: #f0f2f6; padding: 20px; border-radius: 10px; }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# ==========================================\n",
    "# 2. 模擬模型 (Mock Model)\n",
    "# ⚠️ 注意：之後請將此處替換為讀取 pickle 檔的程式碼\n",
    "# ==========================================\n",
    "class MockModel:\n",
    "    def predict_proba(self, features):\n",
    "        # 模擬：根據標題長度和驚嘆號給出一個假機率\n",
    "        # 這裡只是為了展示 UI 效果\n",
    "        score = 0.3\n",
    "        # 簡單規則：有驚嘆號或數字就加分\n",
    "        if features['punct_count'] > 0: score += 0.3\n",
    "        if features['has_digit'] > 0: score += 0.2\n",
    "        if features['title_len'] > 15: score += 0.1\n",
    "        \n",
    "        # 確保在 0~1 之間\n",
    "        final_score = min(score + np.random.uniform(-0.1, 0.1), 0.99)\n",
    "        return [[1-final_score, final_score]]\n",
    "\n",
    "    def predict(self, features):\n",
    "        prob = self.predict_proba(features)[0][1]\n",
    "        return 1 if prob > 0.5 else 0\n",
    "\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    \"\"\"\n",
    "    載入模型函數。\n",
    "    未來請在這裡使用: \n",
    "    model = pickle.load(open('best_model.pkl', 'rb'))\n",
    "    return model\n",
    "    \"\"\"\n",
    "    time.sleep(1) # 模擬載入時間\n",
    "    return MockModel()\n",
    "\n",
    "# ==========================================\n",
    "# 3. 特徵處理函數 (Feature Engineering)\n",
    "# 必須與訓練時的邏輯完全一致\n",
    "# ==========================================\n",
    "def extract_features(text):\n",
    "    text = str(text)\n",
    "    return {\n",
    "        'title_len': len(text),\n",
    "        'punct_count': text.count('!') + text.count('！') + text.count('?') + text.count('？'),\n",
    "        'has_digit': 1 if re.search(r'\\d', text) else 0\n",
    "    }\n",
    "\n",
    "# ==========================================\n",
    "# 4. 主介面邏輯 (Main UI)\n",
    "# ==========================================\n",
    "def main():\n",
    "    # --- 側邊欄 ---\n",
    "    with st.sidebar:\n",
    "        st.image(\"https://cdn-icons-png.flaticon.com/512/2965/2965879.png\", width=100)\n",
    "        st.title(\"T-Forecast V1.0\")\n",
    "        st.info(\"此系統利用 AI 模型預測新聞標題是否具備「爆紅潛力」。\")\n",
    "        st.markdown(\"---\")\n",
    "        st.write(\"🔧 **模型設定**\")\n",
    "        model_type = st.selectbox(\"選擇模型\", [\"XGBoost (Hybrid)\", \"RoBERTa (Deep Learning)\", \"LightGBM (Fast)\"])\n",
    "        threshold = st.slider(\"熱度判定門檻\", 0.0, 1.0, 0.5, 0.05)\n",
    "        st.markdown(\"---\")\n",
    "        st.caption(\"Designed by AI Editor Team\")\n",
    "\n",
    "    # --- 主標題 ---\n",
    "    st.markdown('<p class=\"big-font\">🔥 AI 總編輯：新聞熱度預測系統</p>', unsafe_allow_html=True)\n",
    "    st.write(\"請輸入新聞標題，AI 將為您分析其潛在流量與熱度。\")\n",
    "\n",
    "    # --- 輸入區 ---\n",
    "    news_title = st.text_area(\"📰 請輸入新聞標題：\", height=100, placeholder=\"例如：驚！颱風假真的來了？氣象局最新回應...\")\n",
    "\n",
    "    col1, col2, col3 = st.columns([1, 2, 1])\n",
    "    with col2:\n",
    "        analyze_btn = st.button(\"🚀 開始預測 (Predict)\", type=\"primary\")\n",
    "\n",
    "    # --- 預測邏輯 ---\n",
    "    if analyze_btn:\n",
    "        if not news_title:\n",
    "            st.warning(\"⚠️ 請輸入標題後再試！\")\n",
    "        else:\n",
    "            # 顯示進度條\n",
    "            with st.spinner('🤖 AI 正在分析語意與特徵...'):\n",
    "                # 1. 載入模型\n",
    "                model = load_model()\n",
    "                \n",
    "                # 2. 提取特徵\n",
    "                feats = extract_features(news_title)\n",
    "                \n",
    "                # 3. 預測\n",
    "                probs = model.predict_proba(feats)\n",
    "                prob_hot = probs[0][1]  # 熱門的機率\n",
    "                \n",
    "                time.sleep(0.5) # 增加一點儀式感\n",
    "\n",
    "            # --- 結果顯示區 ---\n",
    "            st.markdown(\"### 📊 分析結果報告\")\n",
    "            \n",
    "            # 使用 container 框起來\n",
    "            with st.container():\n",
    "                # 上半部：結果大字\n",
    "                r_col1, r_col2 = st.columns([1, 1])\n",
    "                \n",
    "                with r_col1:\n",
    "                    st.write(\"#### 預測判定\")\n",
    "                    if prob_hot > threshold:\n",
    "                        st.markdown(f\"# 🔥 **熱門新聞**\")\n",
    "                        st.success(\"這則標題具有高度爆紅潛力！\")\n",
    "                    else:\n",
    "                        st.markdown(f\"# 🧊 **一般新聞**\")\n",
    "                        st.info(\"這則標題較為平鋪直敘。\")\n",
    "                \n",
    "                with r_col2:\n",
    "                    st.write(\"#### 爆紅指數 (Viral Score)\")\n",
    "                    st.metric(label=\"Probability\", value=f\"{prob_hot*100:.1f}%\", delta=f\"門檻: {threshold*100:.0f}%\")\n",
    "                    st.progress(prob_hot)\n",
    "\n",
    "            # 下半部：特徵解析 (Explainability)\n",
    "            st.markdown(\"---\")\n",
    "            st.subheader(\"🧐 AI 看到了什麼？ (特徵解析)\")\n",
    "            \n",
    "            f_col1, f_col2, f_col3 = st.columns(3)\n",
    "            with f_col1:\n",
    "                st.metric(\"字數長度\", f\"{feats['title_len']} 字\", help=\"過短或過長都可能影響閱讀意願\")\n",
    "            with f_col2:\n",
    "                st.metric(\"情緒標點\", f\"{feats['punct_count']} 個\", help=\"驚嘆號與問號能有效提升點擊率\")\n",
    "            with f_col3:\n",
    "                digit_status = \"有 ✅\" if feats['has_digit'] else \"無 ❌\"\n",
    "                st.metric(\"包含數字\", digit_status, help=\"具體的數字通常更吸睛\")\n",
    "\n",
    "            # 若是熱門新聞，給出建議\n",
    "            if prob_hot < threshold:\n",
    "                st.markdown(\"### 💡 AI 修改建議\")\n",
    "                st.write(\"- 試著加入**具體數字**（例如：3大關鍵、6000元）。\")\n",
    "                st.write(\"- 增加**情緒性標點**（！或？）。\")\n",
    "                st.write(\"- 使用**誘餌詞**（例如：驚、曝光、結局）。\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "13ad5077-716e-4eef-b7de-c70b9b0d09f2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
